### ISSUE TITLE
Weird mixed up version resolution on plugins

### ISSUE THREAD

**Issue by atnoya** [alexarchambault/coursier#337] opened 2016-08-31 14:50 UTC
Gonna try to explain the best I can, please excuse my grammatical errors in advance as english is not my mother tongue. And apologies in advance too if it is an already reported bug, but couldn't find anything similar.

So I have a plugin (It's not an open source plugin so I can't really post it here) which has a dependency in scalaz 7.1.3, however the project where that plugin is used explicitly depends on scalaz 7.2.5 (latest at the moment).

There are some incompatibilities between 7.1.X and 7.2.X scalaz versions.

The 'funny' thing is that for some reason when the plugin executes resolves to use the wrong 7.2.5 with the consequent errors.

I am using coursier 1.0.0-M14 (tried too with 1.0.0-M13) and the situation described above works just fine if I disable coursier plugin switching back to normal sbt. Tried SBT versions 0.13.8 and 0.13.11 with same results in both.

**EDIT: It's not using the wrong version of scalaz, it is simply making the scalaz library not available for the plugin, so it won't be able to find any scalaz class**

**Comment by atnoya** [comment] 2016-08-31 21:27
Just to confirm, tested bumping up the version of the scalaz in the plugin to match the same as the project (7.2.5), it all works fine. It's only with discrepant versions.

**Comment by alexarchambault** [comment] 2016-09-04 12:29
I'm not sure I understand what the problem is when your plugin depends on scalaz 7.1. It is expected that it won't find *some* classes when scalaz 7.2 is actually loaded (because of binary incompatibilities), but it should still find some. But the binary incompatibilities are almost guaranteed to make it stop working anyway.

**Comment by atnoya** [comment] 2016-09-04 15:05
@alexarchambault the problem is that the scalaz 7.1 was a dependency of one of the sbt plugins of my project (one that was simply generating some code at compile time). And scalaz 7.2 was an actual dependency explicitly in the build.sbt.

Normal SBT dependency resolution does this correctly and it just works as expected, with coursier enabled for some reason gets the dependencies in build.sbt mixed up with the plugins dependencies, so the expected scalaz functionality is not available for the plugin at compile time when running the code generation task of that plugin.

Hope is clearer now, I know my english isn't great though. So the dependencies of the plugins should not be mixed up with the project dependencies (this is what normal SBT does). Does this make sense?

**Comment by alexarchambault** [comment] 2016-10-30 17:41
@atnoya sbt-coursier itself depends on scalaz 7.2 (since `1.0.0-M14` IIRC), so it's normal to see it pulled from the project update (there shouldn't be a mix up of project / user dependencies, here). Is it still a problem for you? FYI sbt-eclipse and sbt-android switched to scalaz 7.2 too.

**Comment by alexarchambault** [comment] 2016-11-16 16:28
scalaz version conflict seems to be the problem. Closing this for now.

**Closed by alexarchambault** 2016-11-16 16:28 UTC
Labels: plugin
