### ISSUE TITLE
JAR can be missing from empty / meta projects

### ISSUE THREAD

**Issue by alexandru** [alexarchambault/coursier#429] opened 2017-02-01 13:51 UTC
This is a bug in Coursier. When using this dependency:

```scala
"io.monix" %% "monix" % "2.2.1"
```

I get this:

```scala
[trace] Stack trace suppressed: run last *:update for the full output.
[error] (*:update) coursier.ResolutionException: 1 not found
[error]   https://repo1.maven.org/maven2/io/monix/monix_2.11/2.2.1/monix_2.11-2.2.1.jar
[error] Total time: 2 s, completed Feb 1, 2017 3:44:02 PM
```

No JAR is published for `io.monix.monix` because it's a meta project that has multiple sub-projects as dependencies. Instead only the [POM file](https://repo1.maven.org/maven2/io/monix/monix_2.11/2.2.1/monix_2.11-2.2.1.pom) is published.

Also you can see that this file specifies a meta project with sub-projects in it because of the `packaging` specified:

```xml
<packaging>pom</packaging>
```

This is in comparisson with a [normal project](https://repo1.maven.org/maven2/io/monix/monix-reactive_2.12/2.2.1/monix-reactive_2.12-2.2.1.pom) that does publish a JAR:

```xml
<packaging>jar</packaging>
```

This is a public library, I would really appreciate a fix.

Thanks,

**Comment by l15k4** [comment] 2017-02-02 13:14
Yeah, I hit this a few days ago : https://github.com/alexarchambault/coursier/issues/322#issuecomment-276166397 ... It might be a regression because my colleague has been using in all projects for a year without encountering this problem.

**Comment by alexarchambault** [comment] 2017-02-03 00:04
@alexandru @l15k4 Do any of you have a small repro? The following just works fine for me:

```
$ cat build.sbt
scalaVersion := "2.11.8"

libraryDependencies ++= Seq(
  "io.monix" %% "monix" % "2.2.1"
)

$ cat project/build.properties
sbt.version=0.13.13

$ cat project/plugins.sbt
addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.0.0-M15-1")

$ sbt update
[info] Loading project definition from /Users/alexandre/projects/test/monix-coursier/project
[info] Set current project to monix-coursier (in build file:/Users/alexandre/projects/test/monix-coursier/)
[success] Total time: 1 s, completed 3 févr. 2017 01:04:56

**Comment by nvartolomei** [comment] 2017-02-08 16:17
@alexarchambault for me it fails for ` "io.getquill" %% "quill-cassandra" % "1.1.0"` which has monix as a transitive dependency.

**Comment by nvartolomei** [comment] 2017-02-08 16:37
Minimum repo: https://github.com/nvartolomei/coursier-issue-429
Travis CI: https://travis-ci.org/nvartolomei/coursier-issue-429

**Comment by alexarchambault** [comment] 2017-02-28 10:04
This is fixed in the current master. A `1.0.0-M15-2` is about to be released with the fix. Feel free to re-open if you still face this issue.

**Closed by alexarchambault** 2017-02-28 10:04 UTC

**Comment by alexandru** [comment] 2017-02-28 10:06
Oh, thanks a lot @alexarchambault 👍 ❤️
