### ISSUE TITLE
Warning: unrecognized repository inter-project, ignoring it

### ISSUE THREAD

**Issue by fommil** [alexarchambault/coursier#182] opened 2016-02-28 10:55 UTC
I get a lot of noise when I enable the 1.0.0-M9 plugin on this project https://github.com/fommil/imaginary-friend and run `sbt gen-ensime`

e.g.

```
Warning: unrecognized repository inter-project, ignoring it
Repositories:
  ivy:file:/home/fommil/.sbt/0.13/plugins/target/resolution-cache/[organization]/[module](/scala_[scalaVersion])(/sbt_[sbtVersion])/[revision]/resolved.xml.[ext]
  inter-project
  ivy:https://repo.typesafe.com/typesafe/ivy-releases/[organisation]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]
  ivy:https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/[organisation]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]
  ivy:file://${ivy.home}/local/[organisation]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]
  https://repo1.maven.org/maven2/
Resolving com.fommil:imaginary-friend_2.11:1.0.0-SNAPSHOT
...
```

and then a big load of debugging about resolution (which I think is there regardless?)

**Comment by alexarchambault** [comment] 2016-02-28 15:35
I can't get the `Warning: unrecognized repository inter-project, ignoring it` message locally.

**Comment by fommil** [comment] 2016-02-28 15:36
weird

**Comment by fommil** [comment] 2016-02-28 15:36
maybe it was when I did `gen-ensime-project`

**Comment by alexarchambault** [comment] 2016-02-28 15:38
Yep, getting it with `gen-ensime-project`.

**Comment by fommil** [comment] 2016-02-28 15:53
yeah, I have this :smile:

```
alias ensime='sbt gen-ensime gen-ensime-project'
```

**Comment by jeantil** [comment] 2016-07-01 07:29
I have activated coursier globally and I get the same message in a multimodule build when refreshing the build through intellij

**Comment by jeantil** [comment] 2016-07-01 07:46
Ok the warning is issued when running the command `updateSbtClassifiers` in a multimodule sbt project. 
attached is a sample trivial project which exhibits the issue.

[coursier-warn.zip](https://github.com/alexarchambault/coursier/files/343036/coursier-warn.zip)

**Comment by HongxuChen** [comment] 2016-11-20 01:30
Same issue here, my project is using scala-2.12.0 and sbt-0.13.13, single project

**Comment by alexarchambault** [comment] 2017-02-28 14:59
This should fixed in `1.0.0-M15-2`. Feel free to re-open if you still face the issue.

**Closed by alexarchambault** 2017-02-28 14:59 UTC
Labels: bug, plugin

**Comment by nandotorterolo** [comment] 2017-10-18 14:02
still facing the issue, using ohnosequences plugin resolver. 
 sbt.version=0.13.15

> [warn] Unrecognized repository <name> resolver, ignoring it

**Comment by alexarchambault** [comment] 2017-10-31 22:51
@nandotorterolo The [sbt s3 plugin from frugalmechanic](https://github.com/frugalmechanic/fm-sbt-s3-resolver) is supposed to work fine with sbt-coursier. Don't know much about the difference between it and the one from ohnosequences.

**Comment by unkarjedy** [comment] 2023-11-16 18:47
Note, the issue is [fixed](https://github.com/JetBrains/intellij-scala/commit/cced397730039519815943746ce4efca3ddcadc0) in IntelliJ IDEA 2023.3
