### ISSUE TITLE
Should not use repository when pom refer to non existing jar file

### ISSUE THREAD

**Issue by mkotsbak** [alexarchambault/coursier#323] opened 2016-08-13 10:01 UTC
I get this error during update using sbt plugin:

coursier.ResolutionException: 1 not found  https://repo1.maven.org/maven2/bouncycastle/bctsp-jdk14/138/bctsp-jdk14-138.jar

**Comment by mkotsbak** [comment] 2016-08-13 22:04
Ah, I see what is the cause. https://repo1.maven.org/maven2/bouncycastle/bctsp-jdk14/138/ only contains these files, not the jar:

bctsp-jdk14-138.pom                                03-Sep-2009 13:32                 363
bctsp-jdk14-138.pom.md5                            03-Sep-2009 13:32                  54
bctsp-jdk14-138.pom.sha1                           03-Sep-2009 13:32                  62

**Comment by alexarchambault** [comment] 2016-08-23 23:12
This is one of the many regressions in 1.0.0-M13 in the same vein as https://github.com/alexarchambault/coursier/issues/322. Closing this as a duplicate of it. Thanks for the report though!

**Closed by alexarchambault** 2016-08-23 23:12 UTC

**Comment by mkotsbak** [comment] 2016-08-28 18:45
I tried 1.0.0-M14, but still get this problem:

[error] (core/*:update) coursier.ResolutionException: 1 not found
[error]   https://repo1.maven.org/maven2/bouncycastle/bctsp-jdk14/138/bctsp-jdk14-138.jar

**Comment by mielientiev** [comment] 2016-10-15 23:35
@mkotsbak @alexarchambault I have the same issue. The problem that bctsp-jdk14-138 is relocated

**Comment by niij** [comment] 2016-10-25 22:48
I'm having the same issue.  How did you fix it @mielientiev ?
