### ISSUE TITLE
coursier fails to resolve SBT plugins (SNAPSHOT?) published locally

### ISSUE THREAD

**Issue by pfn** [alexarchambault/coursier#207] opened 2016-03-25 00:00 UTC
coursier searched the following locations:
```
  com.hanhuy.sbt:android-sdk-plugin:1.5.21-SNAPSHOT:
    Not found: C:\Users\pfnguyen\.sbt\0.13\plugins\target\resolution-cache\com.hanhuy.sbt\android-sdk-plugin\1.5.21-SNAPSHOT\resolved.xml.xml
    Not found
    Not found: https://repo.typesafe.com/typesafe/ivy-releases/com.hanhuy.sbt/android-sdk-plugin/1.5.21-SNAPSHOT/ivys/ivy.xml
    Not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.hanhuy.sbt/android-sdk-plugin/1.5.21-SNAPSHOT/ivys/ivy.xml
    Not found: C:\Users\pfnguyen\.ivy2\local\com.hanhuy.sbt\android-sdk-plugin\1.5.21-SNAPSHOT\ivys\ivy.xml
    Not found: https://repo1.maven.org/maven2/com/hanhuy/sbt/android-sdk-plugin/1.5.21-SNAPSHOT/android-sdk-plugin-1.5.21-SNAPSHOT.pom
```
it was actually in: 
```
C:\Users\pfnguyen\.ivy2\local\com.hanhuy.sbt\android-sdk-plugin\scala_2.10\sbt_0.13\1.5.21-SNAPSHOT\ivys
```

**Comment by alexarchambault** [comment] 2016-03-25 00:52
Some local quick checks seems to show it works for me. Are you using the latest milestone of coursier (1.0.0-M10)? I was using SBT 0.13.9 in my tests though.

**Comment by pfn** [comment] 2016-03-25 00:54
I was using 1.0.0-M10, published using SBT 0.13.6, but not using coursier to publish (i.e. publish-local without coursier & consume with)

**Comment by alexarchambault** [comment] 2016-03-25 01:04
If I use a non-existing version of the plugin, I get an error like
```
1 error(s):
  com.hanhuy.sbt:android-sdk-plugin;sbtVersion=0.13;scalaVersion=2.10:1.5.21-test0:
    Not found: /Users/alexandre/.sbt/0.13/plugins/target/resolution-cache/com.hanhuy.sbt/android-sdk-plugin/scala_2.10/sbt_0.13/1.5.21-test0/resolved.xml.xml
    Not found
    Not found: https://repo.typesafe.com/typesafe/ivy-releases/com.hanhuy.sbt/android-sdk-plugin/scala_2.10/sbt_0.13/1.5.21-test0/ivys/ivy.xml
    Not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.hanhuy.sbt/android-sdk-plugin/scala_2.10/sbt_0.13/1.5.21-test0/ivys/ivy.xml
    Not found: /Users/alexandre/.ivy2/local/com.hanhuy.sbt/android-sdk-plugin/scala_2.10/sbt_0.13/1.5.21-test0/ivys/ivy.xml
    Not found: https://jcenter.bintray.com/com/hanhuy/sbt/android-sdk-plugin_2.10_0.13/1.5.21-test0/android-sdk-plugin-1.5.21-test0.pom
    Not found: https://repo1.maven.org/maven2/com/hanhuy/sbt/android-sdk-plugin_2.10_0.13/1.5.21-test0/android-sdk-plugin-1.5.21-test0.pom
    Not found: https://oss.sonatype.org/content/repositories/staging/com/hanhuy/sbt/android-sdk-plugin_2.10_0.13/1.5.21-test0/android-sdk-plugin-1.5.21-test0.pom
```

The `~/.ivy2/local` related like has the expected `scala_2.10` and `sbt_0.13` components in particular (`Not found: /Users/alexandre/.ivy2/local/com.hanhuy.sbt/android-sdk-plugin/scala_2.10/sbt_0.13/1.5.21-test0/ivys/ivy.xml`), whereas your error messages don't. That's suspicious...

**Comment by pfn** [comment] 2016-03-25 14:48
Why would my version not be searching the correct plugin path for the ivy cache...

**Comment by pfn** [comment] 2016-03-25 14:53
also fails with 1.0.0-SNAPSHOT

**Comment by pfn** [comment] 2016-03-25 14:57
plugins I have loaded globally, if any might conflict:

```
addSbtPlugin("com.hanhuy.sbt" % "android-sdk-plugin" % "1.5.19")

initialize ~= { _ => sys.props("scala.color") = "true" }
addSbtPlugin("com.github.alexarchambault" % "coursier-sbt-plugin" % "1.0.0-M10")

addSbtPlugin("org.ensime" % "ensime-sbt" % "0.2.1")
addSbtPlugin("com.typesafe.sbt" % "sbt-git" % "0.8.5")
addSbtPlugin("com.hanhuy.sbt" % "key-path" % "0.3")
addSbtPlugin("com.jsuereth" % "sbt-pgp" % "1.0.0")
addSbtPlugin("org.xerial.sbt" % "sbt-sonatype" % "0.5.1")
```

**Comment by alexarchambault** [comment] 2016-03-25 15:24
Tried with this in `~/.sbt/0.13/plugins/build.sbt`, and it still works.

Can you try to run sbt with `COURSIER_VERBOSITY=1` in the env. It should print the repositories it uses, like
```
Repositories:
  ivy:file:/Users/alexandre/.sbt/0.13/plugins/target/resolution-cache/[organization]/[module](/scala_[scalaVersion])(/sbt_[sbtVersion])/[revision]/resolved.xml.[ext]
  inter-project
  ivy:https://repo.typesafe.com/typesafe/ivy-releases/[organisation]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]
  ivy:https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/[organisation]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]
  ivy:file://${ivy.home}/local/[organisation]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]
  https://jcenter.bintray.com/
  https://repo1.maven.org/maven2/
```

The `~/.ivy2/local` line has the `/(scala_[scalaVersion]/)` and `(sbt_[sbtVersion]/)` components in particular here.

**Comment by pfn** [comment] 2016-03-25 15:26
```
Repositories:
  ivy:file:/C:/Users/pfnguyen/.sbt/0.13/plugins/target/resolution-cache/[organization]/[module](/scala_[scalaVersion])(/sbt_[sbtVersion])/[revision]/resolved.xml.[ext]
  inter-project
  ivy:https://repo.typesafe.com/typesafe/ivy-releases/[organisation]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]
  ivy:https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/[organisation]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]
  ivy:file://${ivy.home}/local/[organisation]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]
  https://repo1.maven.org/maven2/
Resolving ...
```

**Comment by pfn** [comment] 2016-03-25 15:27
perhaps Windows paths somehow interfere?

**Comment by alexarchambault** [comment] 2016-04-05 14:37
I wasn't able to reproduce that in a Windows 10 VM, with the master of android-sdk-plugin of a few days ago... It was working fine. I'll look more closely at the code corresponding code. Do you have some kind of reproduction project?

**Comment by pfn** [comment] 2016-04-05 20:36
I don't have a minimal reproduction project, but it happens on all my
github projects as soon as i switch to a snapshot plugin; perhaps there is
a conflict with one of my global plugins.

**Comment by alexarchambault** [comment] 2016-04-29 10:28
The scenario described in https://github.com/alexarchambault/coursier/issues/237 helped me reproduce a similar issue. https://github.com/alexarchambault/coursier/pull/241/commits/f24a71f2fc8a9820e2fb0f072459af680f900e37 should probably fix this one too.

**Comment by pfn** [comment] 2016-04-29 13:21
Ah, so the problem is because I published protify using coursier.

**Comment by alexarchambault** [comment] 2016-05-06 12:06
Should be fixed since https://github.com/alexarchambault/coursier/pull/241/commits/f24a71f2fc8a9820e2fb0f072459af680f900e37 (willl be in 1.0.0-M12, the next milestone).

**Closed by alexarchambault** 2016-05-06 12:06 UTC
Labels: help wanted, plugin
