### ISSUE TITLE
Proxying artifactory doesn't like the sbt plugin on maven central

### ISSUE THREAD

**Issue by eamelink** [alexarchambault/coursier#286] opened 2016-06-22 12:49 UTC
I'm trying to retrieve the sbt-coursier artifact, through a company Artifactory, that proxies Maven Central.

Artifactory refuses to serve me the artifact, with the following error:

```
{
  "errors" : [ {
    "status" : 404,
    "message" : "Failed to transform pom file: The target deployment path 'io/get-coursier/sbt-coursier_2.10_0.13/1.0.0-M12/sbt-coursier-1.0.0-M12.pom' does not match the POM's expected path prefix 'io/get-coursier/sbt-coursier/1.0.0-M12'. Please verify your POM content for correctness and make sure the source path is a valid Maven repository root path."
  } ]
}
```

So it looks like Artifactory does more rigourous checking of the POM than what Maven Central does.

Is this a genuine problem with the published artifact, or is Artifactory wrong here?

**Comment by AlecZorab** [comment] 2016-07-01 11:47
You can disable the artifactory pom checking for that repo. It's under `repository settings->advanced settings->suppress POM consistency checks`

no comment on whether the issue is artifactory or the artifact.

**Comment by alexarchambault** [comment] 2016-07-03 15:34
The SBT plugins distributed via Maven repositories all seem to suffer this issue ([sbt-ensime](http://repo1.maven.org/maven2/org/ensime/sbt-ensime_2.10_0.13/0.6.0/sbt-ensime-0.6.0.pom) does too for example). I'd say it's more an SBT issue.

**Comment by alexarchambault** [comment] 2016-11-16 16:18
Closing this as this seems not specific to coursier.

**Closed by alexarchambault** 2016-11-16 16:18 UTC
Labels: documentation, plugin, question
